apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "shipyard-demo"
spec:
  stages:
    - name: "development"
      sequences:
      - name: "delivery"
        tasks:
        - name: approval
          properties:
            pass: manual
            warning: manual
